// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3Z8EN_j6slIFrSrwa8uDa8q5giKObHk',
    appId: '1:90695386811:web:679844c131b9ffa95f4b9e',
    messagingSenderId: '90695386811',
    projectId: 'cchild-monitoring',
    authDomain: 'cchild-monitoring.firebaseapp.com',
    storageBucket: 'cchild-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALwtO3XK-GW1BbCGXVU_uHlCX8GWsP-0Y',
    appId: '1:90695386811:android:3dda234ac0ab801d5f4b9e',
    messagingSenderId: '90695386811',
    projectId: 'cchild-monitoring',
    storageBucket: 'cchild-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiujkWj2Y8m9nSXIf1EPsEP-bbTfG2EXo',
    appId: '1:90695386811:ios:718419dca7c7e52f5f4b9e',
    messagingSenderId: '90695386811',
    projectId: 'cchild-monitoring',
    storageBucket: 'cchild-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiujkWj2Y8m9nSXIf1EPsEP-bbTfG2EXo',
    appId: '1:90695386811:ios:718419dca7c7e52f5f4b9e',
    messagingSenderId: '90695386811',
    projectId: 'cchild-monitoring',
    storageBucket: 'cchild-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3Z8EN_j6slIFrSrwa8uDa8q5giKObHk',
    appId: '1:90695386811:web:7adf2202c7bbfc225f4b9e',
    messagingSenderId: '90695386811',
    projectId: 'cchild-monitoring',
    authDomain: 'cchild-monitoring.firebaseapp.com',
    storageBucket: 'cchild-monitoring.firebasestorage.app',
  );
}
